# -*- coding: utf-8 -*-
"""Datavirtualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtJHtiw5HWU6fqwbLocEz3iq_NpjBrwU
"""

# -*- coding: utf-8 -*-
"""Datavisualizationproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsQbA0gG7p7mPhuNLlq5EF-BuHf5npYc
"""

import matplotlib.pyplot as plt
import numpy as np

# Sample data
data1 = np.random.randn(100)
data2 = np.random.randn(100) + 2

# Create subplots
fig, ax = plt.subplots(1, 2, figsize=(10, 4))

# Histogram
ax[0].hist(data1, bins=10, color='blue', alpha=0.7, label='Data 1')
ax[0].legend()
ax[0].set_title("Histogram")

# Line plot with colors
ax[1].plot(data1[:20], color='red', label='Line 1')
ax[1].plot(data2[:20], color='green', label='Line 2')
ax[1].legend()
ax[1].set_title("Colored Lines")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [10, 20, 15, 25, 30]

plt.plot(x, y, marker='o')

# Add title and labels
plt.title("Text and Annotation Example")
plt.xlabel("X Values")
plt.ylabel("Y Values")

# Add text
plt.text(2, 22, "Sample Text", fontsize=12, color='blue')

# Add annotation
plt.annotate(
    'Highest Point',
    xy=(5, 30),
    xytext=(3, 35),
    arrowprops=dict(facecolor='black', shrink=0.05)
)

plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

# Data
x = np.random.rand(50)
y = np.random.rand(50)
z = np.random.rand(50)

# 3D plot
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x, y, z, color='purple')

ax.set_xlabel('X Axis')
ax.set_ylabel('Y Axis')
ax.set_zlabel('Z Axis')
ax.set_title('3D Scatter Plot')

plt.show()

!pip install basemap

from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

# Create map
m = Basemap(
    projection='merc',
    llcrnrlat=-60,
    urcrnrlat=80,
    llcrnrlon=-180,
    urcrnrlon=180,
    resolution='c'
)

m.drawcoastlines()
m.drawcountries()
m.fillcontinents(color='lightgreen', lake_color='lightblue')
m.drawmapboundary(fill_color='lightblue')

plt.title("World Map using Basemap")
plt.show()

!pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt

# Load sample dataset
tips = sns.load_dataset("tips")

# Create seaborn scatter plot
sns.scatterplot(
    data=tips,
    x="total_bill",
    y="tip",
    hue="sex"
)

plt.title("Seaborn Visualization")
plt.show()